//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescriptionManager.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class GeneralConfigurations : global::System.Configuration.ApplicationSettingsBase {
        
        private static GeneralConfigurations defaultInstance = ((GeneralConfigurations)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GeneralConfigurations())));
        
        public static GeneralConfigurations Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CH_DIM_BLANK")]
        public string SetBlankFieldValues {
            get {
                return ((string)(this["SetBlankFieldValues"]));
            }
            set {
                this["SetBlankFieldValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MP_FAMILIA")]
        public string GetValuesFromColumn {
            get {
                return ((string)(this["GetValuesFromColumn"]));
            }
            set {
                this["GetValuesFromColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Comp")]
        public string ParamComp {
            get {
                return ((string)(this["ParamComp"]));
            }
            set {
                this["ParamComp"] = value;
            }
        }
    }
}
