#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorDataBase
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IDUGEL_DB")]
	public partial class ConnectorDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDESCRIPTION_MANAGER(DESCRIPTION_MANAGER instance);
    partial void UpdateDESCRIPTION_MANAGER(DESCRIPTION_MANAGER instance);
    partial void DeleteDESCRIPTION_MANAGER(DESCRIPTION_MANAGER instance);
    partial void InsertBLANK_TYPE_NAME(BLANK_TYPE_NAME instance);
    partial void UpdateBLANK_TYPE_NAME(BLANK_TYPE_NAME instance);
    partial void DeleteBLANK_TYPE_NAME(BLANK_TYPE_NAME instance);
    partial void InsertDWG_CUT_FILE_MANAGER(DWG_CUT_FILE_MANAGER instance);
    partial void UpdateDWG_CUT_FILE_MANAGER(DWG_CUT_FILE_MANAGER instance);
    partial void DeleteDWG_CUT_FILE_MANAGER(DWG_CUT_FILE_MANAGER instance);
    partial void InsertNEWAGE(NEWAGE instance);
    partial void UpdateNEWAGE(NEWAGE instance);
    partial void DeleteNEWAGE(NEWAGE instance);
    #endregion
		
		public ConnectorDataClassesDataContext() : 
				base(global::ConnectorDataBase.Properties.Settings.Default.IDUGEL_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectorDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectorDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectorDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConnectorDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DESCRIPTION_MANAGER> DESCRIPTION_MANAGERs
		{
			get
			{
				return this.GetTable<DESCRIPTION_MANAGER>();
			}
		}
		
		public System.Data.Linq.Table<View_Family> View_Families
		{
			get
			{
				return this.GetTable<View_Family>();
			}
		}
		
		public System.Data.Linq.Table<BLANK_TYPE_NAME> BLANK_TYPE_NAMEs
		{
			get
			{
				return this.GetTable<BLANK_TYPE_NAME>();
			}
		}
		
		public System.Data.Linq.Table<DWG_CUT_FILE_MANAGER> DWG_CUT_FILE_MANAGERs
		{
			get
			{
				return this.GetTable<DWG_CUT_FILE_MANAGER>();
			}
		}
		
		public System.Data.Linq.Table<NEWAGE> NEWAGEs
		{
			get
			{
				return this.GetTable<NEWAGE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DESCRIPTION_MANAGER")]
	public partial class DESCRIPTION_MANAGER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NAME_DESCRIPTION;
		
		private string _NAME_IPROP_FIELD;
		
		private string _FAMILY_TYPE;
		
		private string _SCRIPT_DESC;
		
		private string _COMMENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNAME_DESCRIPTIONChanging(string value);
    partial void OnNAME_DESCRIPTIONChanged();
    partial void OnNAME_IPROP_FIELDChanging(string value);
    partial void OnNAME_IPROP_FIELDChanged();
    partial void OnFAMILY_TYPEChanging(string value);
    partial void OnFAMILY_TYPEChanged();
    partial void OnSCRIPT_DESCChanging(string value);
    partial void OnSCRIPT_DESCChanged();
    partial void OnCOMMENTChanging(string value);
    partial void OnCOMMENTChanged();
    #endregion
		
		public DESCRIPTION_MANAGER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_DESCRIPTION", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME_DESCRIPTION
		{
			get
			{
				return this._NAME_DESCRIPTION;
			}
			set
			{
				if ((this._NAME_DESCRIPTION != value))
				{
					this.OnNAME_DESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._NAME_DESCRIPTION = value;
					this.SendPropertyChanged("NAME_DESCRIPTION");
					this.OnNAME_DESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME_IPROP_FIELD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NAME_IPROP_FIELD
		{
			get
			{
				return this._NAME_IPROP_FIELD;
			}
			set
			{
				if ((this._NAME_IPROP_FIELD != value))
				{
					this.OnNAME_IPROP_FIELDChanging(value);
					this.SendPropertyChanging();
					this._NAME_IPROP_FIELD = value;
					this.SendPropertyChanged("NAME_IPROP_FIELD");
					this.OnNAME_IPROP_FIELDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAMILY_TYPE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FAMILY_TYPE
		{
			get
			{
				return this._FAMILY_TYPE;
			}
			set
			{
				if ((this._FAMILY_TYPE != value))
				{
					this.OnFAMILY_TYPEChanging(value);
					this.SendPropertyChanging();
					this._FAMILY_TYPE = value;
					this.SendPropertyChanged("FAMILY_TYPE");
					this.OnFAMILY_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCRIPT_DESC", DbType="VarChar(500)")]
		public string SCRIPT_DESC
		{
			get
			{
				return this._SCRIPT_DESC;
			}
			set
			{
				if ((this._SCRIPT_DESC != value))
				{
					this.OnSCRIPT_DESCChanging(value);
					this.SendPropertyChanging();
					this._SCRIPT_DESC = value;
					this.SendPropertyChanged("SCRIPT_DESC");
					this.OnSCRIPT_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMMENT", DbType="VarChar(200)")]
		public string COMMENT
		{
			get
			{
				return this._COMMENT;
			}
			set
			{
				if ((this._COMMENT != value))
				{
					this.OnCOMMENTChanging(value);
					this.SendPropertyChanging();
					this._COMMENT = value;
					this.SendPropertyChanged("COMMENT");
					this.OnCOMMENTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Family")]
	public partial class View_Family
	{
		
		private string _FAMILIA;
		
		public View_Family()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAMILIA", DbType="VarChar(50)")]
		public string FAMILIA
		{
			get
			{
				return this._FAMILIA;
			}
			set
			{
				if ((this._FAMILIA != value))
				{
					this._FAMILIA = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BLANK_TYPE_NAMES")]
	public partial class BLANK_TYPE_NAME : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _BLANK_TYPE_NAME1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBLANK_TYPE_NAME1Changing(string value);
    partial void OnBLANK_TYPE_NAME1Changed();
    #endregion
		
		public BLANK_TYPE_NAME()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="BLANK_TYPE_NAME", Storage="_BLANK_TYPE_NAME1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BLANK_TYPE_NAME1
		{
			get
			{
				return this._BLANK_TYPE_NAME1;
			}
			set
			{
				if ((this._BLANK_TYPE_NAME1 != value))
				{
					this.OnBLANK_TYPE_NAME1Changing(value);
					this.SendPropertyChanging();
					this._BLANK_TYPE_NAME1 = value;
					this.SendPropertyChanged("BLANK_TYPE_NAME1");
					this.OnBLANK_TYPE_NAME1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DWG_CUT_FILE_MANAGER")]
	public partial class DWG_CUT_FILE_MANAGER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DWG_CUT_FILENAME;
		
		private string _DWG_CUT_BLANK_DIM;
		
		private string _DWG_CUT_MP_COD;
		
		private string _DWG_CUT_MP_DESC_INVENTOR;
		
		private System.Nullable<int> _DWG_CUT_FILE_UPDATED;
		
		private string _CREATE_BY;
		
		private System.Nullable<System.DateTime> _CREATE_DATE;
		
		private string _UPDATE_BY;
		
		private System.Nullable<System.DateTime> _UPDATE_DATE;
		
		private System.Nullable<int> _CUT_FILE_VERSION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDWG_CUT_FILENAMEChanging(string value);
    partial void OnDWG_CUT_FILENAMEChanged();
    partial void OnDWG_CUT_BLANK_DIMChanging(string value);
    partial void OnDWG_CUT_BLANK_DIMChanged();
    partial void OnDWG_CUT_MP_CODChanging(string value);
    partial void OnDWG_CUT_MP_CODChanged();
    partial void OnDWG_CUT_MP_DESC_INVENTORChanging(string value);
    partial void OnDWG_CUT_MP_DESC_INVENTORChanged();
    partial void OnDWG_CUT_FILE_UPDATEDChanging(System.Nullable<int> value);
    partial void OnDWG_CUT_FILE_UPDATEDChanged();
    partial void OnCREATE_BYChanging(string value);
    partial void OnCREATE_BYChanged();
    partial void OnCREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DATEChanged();
    partial void OnUPDATE_BYChanging(string value);
    partial void OnUPDATE_BYChanged();
    partial void OnUPDATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATE_DATEChanged();
    partial void OnCUT_FILE_VERSIONChanging(System.Nullable<int> value);
    partial void OnCUT_FILE_VERSIONChanged();
    #endregion
		
		public DWG_CUT_FILE_MANAGER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DWG_CUT_FILENAME", DbType="VarChar(200)")]
		public string DWG_CUT_FILENAME
		{
			get
			{
				return this._DWG_CUT_FILENAME;
			}
			set
			{
				if ((this._DWG_CUT_FILENAME != value))
				{
					this.OnDWG_CUT_FILENAMEChanging(value);
					this.SendPropertyChanging();
					this._DWG_CUT_FILENAME = value;
					this.SendPropertyChanged("DWG_CUT_FILENAME");
					this.OnDWG_CUT_FILENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DWG_CUT_BLANK_DIM", DbType="VarChar(100)")]
		public string DWG_CUT_BLANK_DIM
		{
			get
			{
				return this._DWG_CUT_BLANK_DIM;
			}
			set
			{
				if ((this._DWG_CUT_BLANK_DIM != value))
				{
					this.OnDWG_CUT_BLANK_DIMChanging(value);
					this.SendPropertyChanging();
					this._DWG_CUT_BLANK_DIM = value;
					this.SendPropertyChanged("DWG_CUT_BLANK_DIM");
					this.OnDWG_CUT_BLANK_DIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DWG_CUT_MP_COD", DbType="VarChar(20)")]
		public string DWG_CUT_MP_COD
		{
			get
			{
				return this._DWG_CUT_MP_COD;
			}
			set
			{
				if ((this._DWG_CUT_MP_COD != value))
				{
					this.OnDWG_CUT_MP_CODChanging(value);
					this.SendPropertyChanging();
					this._DWG_CUT_MP_COD = value;
					this.SendPropertyChanged("DWG_CUT_MP_COD");
					this.OnDWG_CUT_MP_CODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DWG_CUT_MP_DESC_INVENTOR", DbType="VarChar(150)")]
		public string DWG_CUT_MP_DESC_INVENTOR
		{
			get
			{
				return this._DWG_CUT_MP_DESC_INVENTOR;
			}
			set
			{
				if ((this._DWG_CUT_MP_DESC_INVENTOR != value))
				{
					this.OnDWG_CUT_MP_DESC_INVENTORChanging(value);
					this.SendPropertyChanging();
					this._DWG_CUT_MP_DESC_INVENTOR = value;
					this.SendPropertyChanged("DWG_CUT_MP_DESC_INVENTOR");
					this.OnDWG_CUT_MP_DESC_INVENTORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DWG_CUT_FILE_UPDATED", DbType="Int")]
		public System.Nullable<int> DWG_CUT_FILE_UPDATED
		{
			get
			{
				return this._DWG_CUT_FILE_UPDATED;
			}
			set
			{
				if ((this._DWG_CUT_FILE_UPDATED != value))
				{
					this.OnDWG_CUT_FILE_UPDATEDChanging(value);
					this.SendPropertyChanging();
					this._DWG_CUT_FILE_UPDATED = value;
					this.SendPropertyChanged("DWG_CUT_FILE_UPDATED");
					this.OnDWG_CUT_FILE_UPDATEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_BY", DbType="VarChar(50)")]
		public string CREATE_BY
		{
			get
			{
				return this._CREATE_BY;
			}
			set
			{
				if ((this._CREATE_BY != value))
				{
					this.OnCREATE_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATE_BY = value;
					this.SendPropertyChanged("CREATE_BY");
					this.OnCREATE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_BY", DbType="VarChar(50)")]
		public string UPDATE_BY
		{
			get
			{
				return this._UPDATE_BY;
			}
			set
			{
				if ((this._UPDATE_BY != value))
				{
					this.OnUPDATE_BYChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_BY = value;
					this.SendPropertyChanged("UPDATE_BY");
					this.OnUPDATE_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATE_DATE
		{
			get
			{
				return this._UPDATE_DATE;
			}
			set
			{
				if ((this._UPDATE_DATE != value))
				{
					this.OnUPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_DATE = value;
					this.SendPropertyChanged("UPDATE_DATE");
					this.OnUPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUT_FILE_VERSION", DbType="Int")]
		public System.Nullable<int> CUT_FILE_VERSION
		{
			get
			{
				return this._CUT_FILE_VERSION;
			}
			set
			{
				if ((this._CUT_FILE_VERSION != value))
				{
					this.OnCUT_FILE_VERSIONChanging(value);
					this.SendPropertyChanging();
					this._CUT_FILE_VERSION = value;
					this.SendPropertyChanged("CUT_FILE_VERSION");
					this.OnCUT_FILE_VERSIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NEWAGE")]
	public partial class NEWAGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CODIGO;
		
		private string _DESCRICAO;
		
		private string _DESCRICAO_INVENTOR;
		
		private string _FAMILIA;
		
		private string _UNIDADE;
		
		private string _FATOR;
		
		private string _ESPESSURA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCODIGOChanging(string value);
    partial void OnCODIGOChanged();
    partial void OnDESCRICAOChanging(string value);
    partial void OnDESCRICAOChanged();
    partial void OnDESCRICAO_INVENTORChanging(string value);
    partial void OnDESCRICAO_INVENTORChanged();
    partial void OnFAMILIAChanging(string value);
    partial void OnFAMILIAChanged();
    partial void OnUNIDADEChanging(string value);
    partial void OnUNIDADEChanged();
    partial void OnFATORChanging(string value);
    partial void OnFATORChanged();
    partial void OnESPESSURAChanging(string value);
    partial void OnESPESSURAChanged();
    #endregion
		
		public NEWAGE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO", DbType="NChar(10)")]
		public string CODIGO
		{
			get
			{
				return this._CODIGO;
			}
			set
			{
				if ((this._CODIGO != value))
				{
					this.OnCODIGOChanging(value);
					this.SendPropertyChanging();
					this._CODIGO = value;
					this.SendPropertyChanged("CODIGO");
					this.OnCODIGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRICAO", DbType="VarChar(150)")]
		public string DESCRICAO
		{
			get
			{
				return this._DESCRICAO;
			}
			set
			{
				if ((this._DESCRICAO != value))
				{
					this.OnDESCRICAOChanging(value);
					this.SendPropertyChanging();
					this._DESCRICAO = value;
					this.SendPropertyChanged("DESCRICAO");
					this.OnDESCRICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRICAO_INVENTOR", DbType="VarChar(150)")]
		public string DESCRICAO_INVENTOR
		{
			get
			{
				return this._DESCRICAO_INVENTOR;
			}
			set
			{
				if ((this._DESCRICAO_INVENTOR != value))
				{
					this.OnDESCRICAO_INVENTORChanging(value);
					this.SendPropertyChanging();
					this._DESCRICAO_INVENTOR = value;
					this.SendPropertyChanged("DESCRICAO_INVENTOR");
					this.OnDESCRICAO_INVENTORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAMILIA", DbType="VarChar(50)")]
		public string FAMILIA
		{
			get
			{
				return this._FAMILIA;
			}
			set
			{
				if ((this._FAMILIA != value))
				{
					this.OnFAMILIAChanging(value);
					this.SendPropertyChanging();
					this._FAMILIA = value;
					this.SendPropertyChanged("FAMILIA");
					this.OnFAMILIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UNIDADE", DbType="VarChar(20)")]
		public string UNIDADE
		{
			get
			{
				return this._UNIDADE;
			}
			set
			{
				if ((this._UNIDADE != value))
				{
					this.OnUNIDADEChanging(value);
					this.SendPropertyChanging();
					this._UNIDADE = value;
					this.SendPropertyChanged("UNIDADE");
					this.OnUNIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATOR", DbType="VarChar(12)")]
		public string FATOR
		{
			get
			{
				return this._FATOR;
			}
			set
			{
				if ((this._FATOR != value))
				{
					this.OnFATORChanging(value);
					this.SendPropertyChanging();
					this._FATOR = value;
					this.SendPropertyChanged("FATOR");
					this.OnFATORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESPESSURA", DbType="VarChar(12)")]
		public string ESPESSURA
		{
			get
			{
				return this._ESPESSURA;
			}
			set
			{
				if ((this._ESPESSURA != value))
				{
					this.OnESPESSURAChanging(value);
					this.SendPropertyChanging();
					this._ESPESSURA = value;
					this.SendPropertyChanged("ESPESSURA");
					this.OnESPESSURAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
