//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadModelProperties.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResIproperties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResIproperties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CadModelProperties.Resources.ResIproperties", typeof(ResIproperties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLANK_TYPE.
        /// </summary>
        public static string BLANK_TYPE {
            get {
                return ResourceManager.GetString("BLANK_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CH_DIM_BLANK.
        /// </summary>
        public static string CH_DIM_BLANK {
            get {
                return ResourceManager.GetString("CH_DIM_BLANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP_COD.
        /// </summary>
        public static string MP_COD {
            get {
                return ResourceManager.GetString("MP_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP_CUSTOM.
        /// </summary>
        public static string MP_CUSTOM {
            get {
                return ResourceManager.GetString("MP_CUSTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP_DESC_ERP.
        /// </summary>
        public static string MP_DESC_ERP {
            get {
                return ResourceManager.GetString("MP_DESC_ERP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP_DESC_INVENTOR.
        /// </summary>
        public static string MP_DESC_INVENTOR {
            get {
                return ResourceManager.GetString("MP_DESC_INVENTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP_FAMILIA.
        /// </summary>
        public static string MP_FAMILIA {
            get {
                return ResourceManager.GetString("MP_FAMILIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP_FATOR.
        /// </summary>
        public static string MP_FATOR {
            get {
                return ResourceManager.GetString("MP_FATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP_PESO_BRUTO.
        /// </summary>
        public static string MP_PESO_BRUTO {
            get {
                return ResourceManager.GetString("MP_PESO_BRUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP_UNIDADE.
        /// </summary>
        public static string MP_UNIDADE {
            get {
                return ResourceManager.GetString("MP_UNIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQ_COD.
        /// </summary>
        public static string MQ_COD {
            get {
                return ResourceManager.GetString("MQ_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQ_NOME.
        /// </summary>
        public static string MQ_NOME {
            get {
                return ResourceManager.GetString("MQ_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME_APROVADOR.
        /// </summary>
        public static string NOME_APROVADOR {
            get {
                return ResourceManager.GetString("NOME_APROVADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME_DESENHISTA.
        /// </summary>
        public static string NOME_DESENHISTA {
            get {
                return ResourceManager.GetString("NOME_DESENHISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME_PROJETISTA.
        /// </summary>
        public static string NOME_PROJETISTA {
            get {
                return ResourceManager.GetString("NOME_PROJETISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC_ACABAMENTO_PINTURA.
        /// </summary>
        public static string PC_ACABAMENTO_PINTURA {
            get {
                return ResourceManager.GetString("PC_ACABAMENTO_PINTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC_AREA_PINTURA.
        /// </summary>
        public static string PC_AREA_PINTURA {
            get {
                return ResourceManager.GetString("PC_AREA_PINTURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC_COD_DESENHO.
        /// </summary>
        public static string PC_COD_DESENHO {
            get {
                return ResourceManager.GetString("PC_COD_DESENHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC_DESC.
        /// </summary>
        public static string PC_DESC {
            get {
                return ResourceManager.GetString("PC_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC_DESC_COMPLETA.
        /// </summary>
        public static string PC_DESC_COMPLETA {
            get {
                return ResourceManager.GetString("PC_DESC_COMPLETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC_DESC_COMPLETA_CUSTOM.
        /// </summary>
        public static string PC_DESC_COMPLETA_CUSTOM {
            get {
                return ResourceManager.GetString("PC_DESC_COMPLETA_CUSTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC_NOME.
        /// </summary>
        public static string PC_NOME {
            get {
                return ResourceManager.GetString("PC_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC_NUM_DESENHO.
        /// </summary>
        public static string PC_NUM_DESENHO {
            get {
                return ResourceManager.GetString("PC_NUM_DESENHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Number.
        /// </summary>
        public static string PC_NUM_REV {
            get {
                return ResourceManager.GetString("PC_NUM_REV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC_PESO_ACABADO.
        /// </summary>
        public static string PC_PESO_ACABADO {
            get {
                return ResourceManager.GetString("PC_PESO_ACABADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC_PINTURA_INTERNA_DIFERENTE.
        /// </summary>
        public static string PC_PINTURA_INTERNA_DIFERENTE {
            get {
                return ResourceManager.GetString("PC_PINTURA_INTERNA_DIFERENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC_TIPO_PINTURA.
        /// </summary>
        public static string PC_TIPO_PINTURA {
            get {
                return ResourceManager.GetString("PC_TIPO_PINTURA", resourceCulture);
            }
        }
    }
}
