//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WConnector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FilterNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilterNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WConnector.Resources.FilterNames", typeof(FilterNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Inventor.
        /// </summary>
        internal static string DescricaoInventor {
            get {
                return ResourceManager.GetString("DescricaoInventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espessura.
        /// </summary>
        internal static string Espessura {
            get {
                return ResourceManager.GetString("Espessura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Família.
        /// </summary>
        internal static string Familia {
            get {
                return ResourceManager.GetString("Familia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fator de Conversão.
        /// </summary>
        internal static string FatorConversao {
            get {
                return ResourceManager.GetString("FatorConversao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODIGO.
        /// </summary>
        internal static string FilterCodigo {
            get {
                return ResourceManager.GetString("FilterCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRICAO_INVENTOR.
        /// </summary>
        internal static string FilterDescInventor {
            get {
                return ResourceManager.GetString("FilterDescInventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRICAO.
        /// </summary>
        internal static string FilterDescricao {
            get {
                return ResourceManager.GetString("FilterDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESPESSURA.
        /// </summary>
        internal static string FilterEspessura {
            get {
                return ResourceManager.GetString("FilterEspessura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAMILIA.
        /// </summary>
        internal static string FilterFamilia {
            get {
                return ResourceManager.GetString("FilterFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade.
        /// </summary>
        internal static string Unidade {
            get {
                return ResourceManager.GetString("Unidade", resourceCulture);
            }
        }
    }
}
